log_db:
  user: userclouds
  dbname: status_00000000000000000000000000000000
  host: localhost
  dbdriver: postgres
  dbproduct: postgres
  port: 5432

internal_server:
  protocol: http
  host: 127.0.0.1
  port: 5501

svc_listener:
  protocol: http
  host: localhost
  port: 5500

console_tenant_id: 41ab79a8-0dff-418e-9d42-e1694469120a
